### ISSUE TITLE
AppStore - App Not Available - RU Region

### ISSUE THREAD

**Issue by endervad** [avdept/JellyBoxPlayer#36]
Hi!

I'd love to try your app since just recently I was looking for a native Jellyfin music app for macOS. However, it seems to be not available in Russia where I live. Can't join TestFlight either since it's full. Can you please make it available in RU region?

<img width="372" alt="Screenshot 2024-04-11 at 10 29 46" src="https://github.com/avdept/JellyBoxPlayer/assets/10913278/48aaac98-a0c5-44ba-9b10-31880a192aaf">

**Comment by avdept** [comment]
Sorry, but app is not planned to be available in Ru region due to political reasons.
