### ISSUE TITLE
Frozen screen with “select library” at the top

### ISSUE THREAD

**Issue by josephgeorgep** [avdept/JellyBoxPlayer#41]
Today, my player got froze with the following screen

<img width="619" alt="FrozenJellyBox" src="https://github.com/avdept/JellyBoxPlayer/assets/82633410/a0b78930-e2a9-4974-967b-955d6d68b8bf">

I even tried re-installing the player, but the same black screen will come up when I open the app again. The Jellyfin server and the libraries are working fine on the web and another music app like 'Fintunes"

**Comment by avdept** [comment]
Hey, I checked bug tracker and I see the issue you're having(thats 401 error which means session expired), however for some reason its not properly handling it(redirect you to login screen). I'll take a look today and submit a fix, thanks for reporting!

**Comment by josephgeorgep** [comment]
Thank you Alex :)

> Hey, I checked bug tracker and I see the issue you're having(thats 401 error which means session expired), however for some reason its not properly handling it(redirect you to login screen). I'll take a look today and submit a fix, thanks for reporting!

**Comment by avdept** [comment]
Hey @josephgeorgep I've submitted new version to appstore, which fixes your issue, but also bypasses library selection screen if you already selected it(but you'll need to select it at least once on new version)

**Comment by josephgeorgep** [comment]
> Hey @josephgeorgep I've submitted new version to appstore, which fixes your issue, but also bypasses library selection screen if you already selected it(but you'll need to select it at least once on new version). Should be available in appstore tomorrow

Thankyou Alex :) I just installed the jellybox, and everything is working fine now. I appreciate your support here

**Comment by avdept** [comment]
> > Hey @josephgeorgep I've submitted new version to appstore, which fixes your issue, but also bypasses library selection screen if you already selected it(but you'll need to select it at least once on new version). Should be available in appstore tomorrow
> 
> Thankyou Alex :) I just installed the jellybox, and everything is working fine now. I appreciate your support here

Glad it works. Feels free to report any other issue/feature request.

Closing this for now as resolved.

**Comment by dronnikovigor** [comment]
Hi, i'm facing the same issue on 1.8.4 build on Android (just fresh install). I can only Logout 
![telegram-cloud-photo-size-2-5363824952366719771-y](https://github.com/user-attachments/assets/0bf6f824-11f9-43ca-ad4a-05e493ce8766)

**Comment by avdept** [comment]
> Hi, i'm facing the same issue on 1.8.4 build on Android (just fresh install). I can only Logout ![telegram-cloud-photo-size-2-5363824952366719771-y](https://private-user-images.githubusercontent.com/4175117/361861342-0bf6f824-11f9-43ca-ad4a-05e493ce8766.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NzEzMDUsIm5iZiI6MTcyNDc3MTAwNSwicGF0aCI6Ii80MTc1MTE3LzM2MTg2MTM0Mi0wYmY2ZjgyNC0xMWY5LTQzY2EtYWQ0YS0wNWU0OTNjZTg3NjYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMTUwMzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzMzN2IyYzljZTg2MmMwZTA1ZjlhZDEyZWI0Mjg4OTc2YmJiYjNmYThkYjc5NjZmYTUyOTdmYTYyNTg1MzAxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9JyHO1J3OdhkJApCx9ZiQTukq7AkK07eJIqdqQmtZYA)

Do you have music libraries in your jellyfin installation?

**Comment by dronnikovigor** [comment]
Oh, wait :) It's only for music. My apologies then

**Comment by avdept** [comment]
> Oh, wait :) It's only for music. My apologies then

Haha, it's alright. You should start using Jellyfin for music too, such a nice tool!
