### ISSUE TITLE
"This beta isn't accepting any new testers right now."

### ISSUE THREAD

**Issue by gabrielwhite** [avdept/JellyBoxPlayer#45]
Would it be possible to open up more invites for MacOS on TestFlight?

Thanks!

**Comment by avdept** [comment]
Hey @gabrielwhite, you can download app from appstore now. I dont have any testing going right now, so test flight version and appstore is the same. Although thanks for letting me know that it's full, I'll try to clean it up a bit to have few extra free seats

**Comment by gabrielwhite** [comment]
Ah, thank you! Maybe worth updating the README to direct users to the app store, as it's not clear how to access the app on either MacOS or iOS without TestFlight. @avdept

**Comment by avdept** [comment]
> Ah, thank you! Maybe worth updating the README to direct users to the app store, as it's not clear how to access the app on either MacOS or iOS without TestFlight. @avdept

I posted links at the top of readme, but until I have something that needs to be tested I'll hide testing section in readme. Thanks for pointing me out!
