### ISSUE TITLE
Allow login without password

### ISSUE THREAD

**Issue by gabrielwhite** [avdept/JellyBoxPlayer#51]
I had to add a password to my Jellyfin account to use the app (passwords aren't mandatory on Jellyfin). Maybe consider removing the error check for no-password?

**Comment by avdept** [comment]
Good idea, I'll check how its implemented in their API

**Comment by avdept** [comment]
@gabrielwhite I got this implemented. I just submitted v1.8.3 to appstores and put APK file to releases section. Once its gets approved you can use passwordless login
