### ISSUE TITLE
FEATURE: Random sort order

### ISSUE THREAD

**Issue by gabrielwhite** [avdept/JellyBoxPlayer#52]
Jellybox is the media player I've been wanting - it's fantastically simple. I use my media player to rediscover content in my collection and so would really value a "Random" sort order. This ideally would reshuffle the albums every time I return to the library view. Thanks!

**Comment by avdept** [comment]
Hey, thanks for feedback. I will check whether jellyfin provides a way to sort randomly!

**Comment by gabrielwhite** [comment]
From the Jellyfin native app:

![image](https://github.com/user-attachments/assets/fb30d374-c4f2-4901-820b-791443e6ba6a)

**Comment by avdept** [comment]
@gabrielwhite 
Ok, I just did quick test and got it working in random order. I will submit new versions to appstore in few minutes, but it will take some time for apple to review and approve it.

**Comment by gabrielwhite** [comment]
Awesome. Thank you!

**Comment by avdept** [comment]
@gabrielwhite Added random sorting order as per your request. If you use android version you can download it from releases tab. If you use appstrore - gotta wait a bit until its reviewed and approved, usually takes ~12 hours

And thanks for suggesting, just found out few albums I missed by using random order
